"use client";
import { useEffect, useState } from "react";
import { ExternalLink } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { api } from "@/lib/api";

type Refs = Awaited<ReturnType<typeof api.references>>["references"];

export default function ReferencesPage() {
  const [refs, setRefs] = useState<Refs>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    api.references().then((r) => setRefs(r.references)).catch((e) => setError(e.message));
  }, []);
  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <div>
        <h1 className="text-2xl font-semibold sm:text-3xl">References and data provenance</h1>
        <p className="text-sm text-muted-foreground">
          All numerical data used by the calculation engine come from the sources below. No attenuation coefficient, composition or density is generated by an AI model.
        </p>
      </div>
      {error && <p className="text-sm text-destructive">{error}</p>}
      {refs.map((t) => (
        <Card key={t.topic}>
          <CardHeader>
            <CardTitle>{t.topic}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {t.items.map((i) => (
              <div key={i.id} className="space-y-1 text-sm">
                <p>{i.citation}</p>
                <p className="flex flex-wrap gap-3 text-xs">
                  {i.doi && (
                    <a className="link" href={`https://doi.org/${i.doi}`} target="_blank" rel="noreferrer">
                      doi:{i.doi}
                    </a>
                  )}
                  {i.url && (
                    <a className="inline-flex items-center gap-1 link" href={i.url} target="_blank" rel="noreferrer">
                      {new URL(i.url).hostname} <ExternalLink className="size-3" />
                    </a>
                  )}
                </p>
                <p className="text-xs text-muted-foreground">Used for: {i.used_for}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      ))}
      <Card>
        <CardHeader>
          <CardTitle>Methodology notes</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm text-muted-foreground">
          <p>Mixture rule: (μ/ρ) = Σ wᵢ (μ/ρ)ᵢ with elemental mass fractions wᵢ. Compounds are treated as mixtures of free atoms (no chemical-binding or crystal effects), as in XCOM.</p>
          <p>
            Interpolation: log-log cubic splines for scattering and (threshold-factored) pair production; photoelectric absorption uses a log-log cubic spline above the K edge and
            piecewise log-log linear interpolation between absorption edges below it, never across an edge.
          </p>
          <p>Shielding quantities (μ, HVL, TVL, MFP, transmission) assume narrow-beam geometry; broad-beam build-up is not included.</p>
          <p>Polymer compositions are derived from ideal repeat units; the elemental mass fractions do not depend on the degree of polymerisation.</p>
        </CardContent>
      </Card>
    </div>
  );
}
